# Generated by Django 3.1.1 on 2020-09-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=50, verbose_name='Nome do projeto')),
                ('local', models.CharField(max_length=50, verbose_name='CEP')),
                ('media_anual', models.CharField(max_length=5, verbose_name='Média anual de consumo')),
                ('type', models.CharField(choices=[('M', 'Monofásica'), ('B', 'Bifásica'), ('T', 'Trifásica')], max_length=1, verbose_name='Tipo de Ligação')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novo Projeto',
                'ordering': ['id'],
            },
        ),
    ]
